### ISSUE TITLE
setup-pgbouncer.sh missing steps for submodoule init

### ISSUE THREAD

**Issue by svaderia** [gzaniolo/emulab_scripts_and_files#1]
If you are setting up the pgbouncer for the first time on emulab, you need to do git submodule init thingy

**Comment by gzaniolo** [comment]
I am on my phone but I added it, hopefully it works lol. Do I need to add you guys to the project for you to be able to commit?

**Comment by gzaniolo** [comment]
Ok you should be invited atl

**Comment by svaderia** [comment]
perfect, thanks
